# coding: utf-8

# flake8: noqa
"""
    BringAuto Fleet Management v2 API

    Specification for BringAuto fleet backend HTTP API

    The version of the OpenAPI document: 1.3.0
    Contact: fleet@bringauto.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from fleet-management-http-client-python.models.car import Car
from fleet-management-http-client-python.models.car_state import CarState
from fleet-management-http-client-python.models.car_status import CarStatus
from fleet-management-http-client-python.models.error import Error
from fleet-management-http-client-python.models.gnss_position import GNSSPosition
from fleet-management-http-client-python.models.mobile_phone import MobilePhone
from fleet-management-http-client-python.models.order import Order
from fleet-management-http-client-python.models.order_state import OrderState
from fleet-management-http-client-python.models.order_status import OrderStatus
from fleet-management-http-client-python.models.platform_hw import PlatformHW
from fleet-management-http-client-python.models.route import Route
from fleet-management-http-client-python.models.route_visualization import RouteVisualization
from fleet-management-http-client-python.models.stop import Stop
