# coding: utf-8

"""
    BringAuto Fleet Management v2 API

    Specification for BringAuto fleet backend HTTP API

    The version of the OpenAPI document: 1.3.0
    Contact: fleet@bringauto.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fleet-management-http-client-python.models.order_state import OrderState

class TestOrderState(unittest.TestCase):
    """OrderState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderState:
        """Test OrderState
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderState`
        """
        model = OrderState()
        if include_optional:
            return OrderState(
                id = 1,
                status = 'to_accept',
                order_id = 1,
                timestamp = 1616425200000
            )
        else:
            return OrderState(
                status = 'to_accept',
                order_id = 1,
        )
        """

    def testOrderState(self):
        """Test OrderState"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
