# coding: utf-8

"""
    BringAuto Fleet Management v2 API

    Specification for BringAuto fleet backend HTTP API

    The version of the OpenAPI document: 1.3.0
    Contact: fleet@bringauto.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fleet-management-http-client-python.models.car import Car

class TestCar(unittest.TestCase):
    """Car unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Car:
        """Test Car
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Car`
        """
        model = Car()
        if include_optional:
            return Car(
                id = 1,
                platform_hw_id = 1,
                name = 'BAT-2022-01',
                car_admin_phone = fleet-management-http-client-python.models.mobile_phone.MobilePhone(
                    phone = '+420123456789', ),
                default_route_id = 1,
                under_test = False
            )
        else:
            return Car(
                platform_hw_id = 1,
                name = 'BAT-2022-01',
                car_admin_phone = fleet-management-http-client-python.models.mobile_phone.MobilePhone(
                    phone = '+420123456789', ),
        )
        """

    def testCar(self):
        """Test Car"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
