# coding: utf-8

"""
    BringAuto Fleet Management v2 API

    Specification for BringAuto fleet backend HTTP API

    The version of the OpenAPI document: 1.3.0
    Contact: fleet@bringauto.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fleet-management-http-client-python.api.route_api import RouteApi


class TestRouteApi(unittest.TestCase):
    """RouteApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RouteApi()

    def tearDown(self) -> None:
        pass

    def test_create_route(self) -> None:
        """Test case for create_route

        Create a new Route.
        """
        pass

    def test_delete_route(self) -> None:
        """Test case for delete_route

        Delete a Route with the specified ID.
        """
        pass

    def test_get_route(self) -> None:
        """Test case for get_route

        Find a single Route with the specified ID.
        """
        pass

    def test_get_route_visualization(self) -> None:
        """Test case for get_route_visualization

        Find Route Visualization for a Route identified by the route's ID.
        """
        pass

    def test_get_routes(self) -> None:
        """Test case for get_routes

        Find and return all existing Routes.
        """
        pass

    def test_redefine_route_visualization(self) -> None:
        """Test case for redefine_route_visualization

        Redefine Route Visualization for an existing Route.
        """
        pass

    def test_update_route(self) -> None:
        """Test case for update_route

        Update already existing Route.
        """
        pass


if __name__ == '__main__':
    unittest.main()
