# coding: utf-8

"""
    BringAuto Fleet Management v2 API

    Specification for BringAuto fleet backend HTTP API

    The version of the OpenAPI document: 1.3.0
    Contact: fleet@bringauto.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fleet-management-http-client-python.models.car_status import CarStatus

class TestCarStatus(unittest.TestCase):
    """CarStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCarStatus(self):
        """Test CarStatus"""
        # inst = CarStatus()

if __name__ == '__main__':
    unittest.main()
