# coding: utf-8

"""
    BringAuto Fleet Management v2 API

    Specification for BringAuto fleet backend HTTP API

    The version of the OpenAPI document: 1.3.0
    Contact: fleet@bringauto.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fleet-management-http-client-python.api.security_api import SecurityApi


class TestSecurityApi(unittest.TestCase):
    """SecurityApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SecurityApi()

    def tearDown(self) -> None:
        pass

    def test_login(self) -> None:
        """Test case for login

        """
        pass

    def test_token_get(self) -> None:
        """Test case for token_get

        """
        pass

    def test_token_refresh(self) -> None:
        """Test case for token_refresh

        """
        pass


if __name__ == '__main__':
    unittest.main()
