# coding: utf-8

"""
    BringAuto Fleet Management v2 API

    Specification for BringAuto fleet backend HTTP API

    The version of the OpenAPI document: 1.3.0
    Contact: fleet@bringauto.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fleet_management_http_client_python.api.car_state_api import CarStateApi


class TestCarStateApi(unittest.TestCase):
    """CarStateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CarStateApi()

    def tearDown(self) -> None:
        pass

    def test_add_car_state(self) -> None:
        """Test case for add_car_state

        Add a new Car State.
        """
        pass

    def test_get_all_car_states(self) -> None:
        """Test case for get_all_car_states

        Find one or all Car States for a Car with the specified ID.
        """
        pass

    def test_get_car_states(self) -> None:
        """Test case for get_car_states

        Find one or all Car States for a given Car.
        """
        pass


if __name__ == '__main__':
    unittest.main()
