# coding: utf-8

"""
    BringAuto Fleet Management v2 API

    Specification for BringAuto fleet backend HTTP API

    The version of the OpenAPI document: 3.4.4
    Contact: fleet@bringauto.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fleet_management_http_client_python.api.tenant_api import TenantApi


class TestTenantApi(unittest.TestCase):
    """TenantApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TenantApi()

    def tearDown(self) -> None:
        pass

    def test_delete_tenant(self) -> None:
        """Test case for delete_tenant

        Delete Tenant with the given ID.
        """
        pass

    def test_get_tenants(self) -> None:
        """Test case for get_tenants

        Find and return all existing Tenant.
        """
        pass


if __name__ == '__main__':
    unittest.main()
