# coding: utf-8

"""
    BringAuto Fleet Management v2 API

    Specification for BringAuto fleet backend HTTP API

    The version of the OpenAPI document: 1.3.0
    Contact: fleet@bringauto.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fleet_management_http_client_python.models.car_state import CarState

class TestCarState(unittest.TestCase):
    """CarState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CarState:
        """Test CarState
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CarState`
        """
        model = CarState()
        if include_optional:
            return CarState(
                id = 1,
                status = 'idle',
                fuel = 80,
                car_id = 1,
                speed = 20.5,
                position = fleet_management_http_client_python.models.gnss_position.GNSSPosition(
                    latitude = 49.204117, 
                    longitude = 16.606525, 
                    altitude = 400.25, )
            )
        else:
            return CarState(
                status = 'idle',
                car_id = 1,
        )
        """

    def testCarState(self):
        """Test CarState"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
