# coding: utf-8

"""
    BringAuto Fleet Management v2 API

    Specification for BringAuto fleet backend HTTP API

    The version of the OpenAPI document: 3.4.0
    Contact: fleet@bringauto.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fleet_management_http_client_python.api.car_action_api import CarActionApi


class TestCarActionApi(unittest.TestCase):
    """CarActionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CarActionApi()

    def tearDown(self) -> None:
        pass

    def test_get_car_action_states(self) -> None:
        """Test case for get_car_action_states

        Finds car action states for a Car with given carId.
        """
        pass

    def test_pause_car(self) -> None:
        """Test case for pause_car

        Finds and pauses a Car with given carId, if not already paused. Sets car action status to PAUSED if it is not in PAUSED action status already.
        """
        pass

    def test_unpause_car(self) -> None:
        """Test case for unpause_car

        Finds and unpauses a Car with given carId, if paused. Sets car action status to NORMAL only if it is in PAUSED action status.
        """
        pass


if __name__ == '__main__':
    unittest.main()
