# coding: utf-8

"""
    BringAuto Fleet Management v2 API

    Specification for BringAuto fleet backend HTTP API

    The version of the OpenAPI document: 1.3.0
    Contact: fleet@bringauto.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fleet_management_http_client_python.api.order_api import OrderApi


class TestOrderApi(unittest.TestCase):
    """OrderApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrderApi()

    def tearDown(self) -> None:
        pass

    def test_create_order(self) -> None:
        """Test case for create_order

        Create a new Order.
        """
        pass

    def test_delete_order(self) -> None:
        """Test case for delete_order

        Delete an Order with the specified ID.
        """
        pass

    def test_get_order(self) -> None:
        """Test case for get_order

        Find an existing Order by its ID and return it.
        """
        pass

    def test_get_orders(self) -> None:
        """Test case for get_orders

        Find all currently existing Orders.
        """
        pass

    def test_get_updated_orders(self) -> None:
        """Test case for get_updated_orders

        Get updated Orders for a given Car specified by its ID.
        """
        pass


if __name__ == '__main__':
    unittest.main()
