# coding: utf-8

"""
    BringAuto Fleet Management v2 API

    Specification for BringAuto fleet backend HTTP API

    The version of the OpenAPI document: 1.3.0
    Contact: fleet@bringauto.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fleet_management_http_client_python.models.stop import Stop

class TestStop(unittest.TestCase):
    """Stop unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Stop:
        """Test Stop
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Stop`
        """
        model = Stop()
        if include_optional:
            return Stop(
                id = 1,
                name = 'Lidická',
                position = fleet_management_http_client_python.models.gnss_position.GNSSPosition(
                    latitude = 49.204117, 
                    longitude = 16.606525, 
                    altitude = 400.25, ),
                notification_phone = fleet_management_http_client_python.models.mobile_phone.MobilePhone(
                    phone = '+420123456789', )
            )
        else:
            return Stop(
                name = 'Lidická',
                position = fleet_management_http_client_python.models.gnss_position.GNSSPosition(
                    latitude = 49.204117, 
                    longitude = 16.606525, 
                    altitude = 400.25, ),
        )
        """

    def testStop(self):
        """Test Stop"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
